backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "images"
collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    files:
      - file: "content/_index.md"
        label: "Home"
        name: home
        fields:
          - label: "Banner Image + CTA Button"
            name: banner-cta
            widget: "object"
            fields:
              [
                { label: "Heading Text", name: "heading", widget: string },
                { label: "Button Text", name: "button", widget: string },
                { label: "Background Image", name: "image", widget: image },
                { label: "Heading Alignment", name: "align", widget: "select", options: ["left", "center", "right", "left-bottom", "right-bottom"] }
              ]
          - label: "Body"
            name: "body"
            widget: "markdown"
      - file: "content/about.md"
        label: "About us"
        name: about
        fields:
          - label: "Title"
            name: "title"
            widget: string
          - label: "Body"
            name: "body"
            widget: "markdown"
      - file: "content/events.md"
        label: "Events"
        name: events
        fields:
          - label: "Title"
            name: "title"
            widget: string
          - label: "Body"
            name: "body"
            widget: "markdown"
      - file: "content/contact.md"
        label: "Contact us"
        name: contact
        fields:
          - label: "Title"
            name: "title"
            widget: string
          - label: "Body"
            name: "body"
            widget: "markdown"
      - file: "content/support.md"
        label: "Support"
        name: support
        fields:
          - label: "Title"
            name: "title"
            widget: string
          - label: "Body"
            name: "body"
            widget: "markdown"
  - name: "programmes"
    label: "Programmes"
    folder: "content/programmes"
    path: "{{slug}}/index"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: string
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Closing date"
        name: "date"
        widget: "datetime"