site_url: https://impacthubauckland.nz
backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    path: "{{slug}}"
    fields:
      - label: "Order sequence"
        name: "weight"
        widget: number
      - label: "Title"
        name: "title"
        widget: string
      - label: "Body"
        name: "body"
        widget: markdown
  - name: "programmes"
    label: "Programmes"
    folder: "content/programmes"
    path: "{{slug}}/index"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: string
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Closing date"
        name: "date"
        widget: "datetime"
  - name: "people"
    label: "People"
    folder: "content/about/people"
    create: true
    fields:
      - label: "Name"
        name: "name"
        widget: string
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Photo"
        name: "photo"
        widget: "image"
  - name: "offers"
    label: "Offers"
    folder: "content/iha/offers"
    create: true
    fields:
      - label: "Name"
        name: "name"
        widget: string
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Image"
        name: "image"
        widget: "image"
  - name: "focus"
    label: "Focus"
    folder: "content/iha/focus"
    path: "{{slug}}"
    create: true
    fields:
      - label: "Name"
        name: "title"
        widget: string
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "LinkedIn Url"
        name: "linkedin"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "image"